# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 1
  # - nightly
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.test("Couchzilla",coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"))'
  - julia -e 'cd(Pkg.dir("Couchzilla")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("Couchzilla")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
#  - julia -e 'cd(Pkg.dir("Couchzilla")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
